[package]
name = "ppapi"
version = "0.0.1"
authors = ["Richard Diamond"]
links = "helper"
build = "src/build.rs"

[lib]
name = "ppapi"
path = "src/lib/lib.rs"

[dependencies.http]
git = "https://github.com/DiamondLovesYou/rust-http.git"

[dependencies.openssl]
git = "https://github.com/DiamondLovesYou/rust-openssl.git"

[build-dependencies.pnacl-build-helper]
git = "https://github.com/DiamondLovesYou/cargo-pnacl-helper.git"
